name: deliver_it_client
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  firebase_core: ^2.24.2
  get_it: ^7.7.0
  provider: ^6.1.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  flutter_local_notifications: ^17.2.1+2
  firebase_messaging: ^14.7.10
  url_launcher: ^6.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - images/svgs/
    - images/imgs/

  
  

  
  

  
  
  
  
  
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/cairo/Cairo-Regular.ttf
        - asset: fonts/cairo/Cairo-Medium.ttf
       
          
